version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
